-- Migration: 03 — Create `orgs` table
-- Phase:     1 (Org/User Schema, Enums, RLS)
-- Created:   2026-05-13
--
-- Purpose:
--   The `orgs` table is the root of org-scoped authorization in v1. Every
--   calling Airiam app (BDT today, AIP later, future apps) asserts a stable
--   `org_id` for each submission; that `org_id` references this table.
--
--   v1 does NOT manage org provisioning through the application — rows are
--   inserted manually (or via the dev seed in migration 09). Programmatic
--   org admin is a post-v1 concern.
--
-- Columns:
--   id         : stable identifier asserted by callers. UUID; default
--                generated by pgcrypto if not supplied.
--   name       : human-readable display name (e.g., "ATD internal", "BDT").
--   status     : free-form lifecycle marker. Default 'active'. v1 uses
--                'active' only; future values like 'suspended' or 'archived'
--                are additive.
--   created_at : insert timestamp.
--   updated_at : last-modified timestamp; maintained by trigger below.
--   deleted_at : soft-delete sentinel. Provider/repository wrappers filter
--                `deleted_at is null` by default (see architecture doc).
--
-- Idempotency:
--   Uses `IF NOT EXISTS` for the table and trigger. Safe to re-run.
--
-- Rollback:
--   `DROP TRIGGER ... ON orgs; DROP FUNCTION set_updated_at(); DROP TABLE orgs;`
--   The function is shared with later tables, so only drop it when removing
--   every table that uses it.

create table if not exists orgs (
  id         uuid        primary key default gen_random_uuid(),
  name       text        not null,
  status     text        not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

-- Shared trigger helper for `updated_at` maintenance. Created here because
-- `orgs` is the first table that needs it; later tables reuse the same
-- function. Wrapped in `or replace` so re-running this migration is safe.
create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists orgs_set_updated_at on orgs;
create trigger orgs_set_updated_at
before update on orgs
for each row execute function set_updated_at();

comment on table  orgs                is 'Authorized calling organizations. Root of v1 org-scoped authorization.';
comment on column orgs.id             is 'Stable identifier asserted by callers (Source A) or returned to monitoring (Source B).';
comment on column orgs.status         is 'Lifecycle marker. v1 uses "active" only.';
comment on column orgs.deleted_at     is 'Soft-delete sentinel. Provider wrappers filter `is null` by default.';
